version: '3.8'

services:
  bd:
    container_name: imagina-bd
    image: 'postgis/postgis:14-3.2'
    volumes:
      - ./basededatos:/var/lib/postgresql/data
    networks:
      - red-imagina
    ports:
      - ${BD_PUERTO}:5432
    environment:
      POSTGRES_USER: ${BD_USUARIO}
      POSTGRES_PASSWORD: ${BD_CLAVE}
      POSTGRES_DB: ${BD_NOMBRE}
  cache:
    container_name: imagina-cache
    image: redis:6.2-alpine
    networks:
      - red-imagina
    ports:
      - ${CACHE_PUERTO}:6379
  admin:
    container_name: imagina-admin
    image: 'dpage/pgadmin4'
    ports:
      - 5050:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - bd
    networks:
      - red-imagina
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'

networks:
  red-imagina:
